Fix: Notification type issues
blocknative/notify pull request #166
Opened 2020-09-24 03:25 UTC by aaronbarnardsound

This PR addresses some basic type issues with notifications that were showing up now that Svelte files are being seen correctly by the TypeScript compiler.

2020-09-24 22:51 UTC, liamaharon requested changes

2020-09-24 22:51 UTC, liamaharon commented on src/notify.ts
> +  console.log('LOCALLLLL')
:eyes:

2020-09-24 23:21 UTC, aaronbarnardsound commented on src/notify.ts
> +  console.log('LOCALLLLL')
Oops thanks for picking that one up haha

2020-09-25 00:19 UTC, liamaharon approved these changes

2020-09-25 00:19 UTC, merged